kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 15020
    hostPort: 15020
    protocol: TCP
  - containerPort: 30080
    hostPort: 8080
    protocol: TCP
  - containerPort: 30443
    hostPort: 8443
    protocol: TCP
  - containerPort: 15029
    hostPort: 15029
    protocol: TCP
  - containerPort: 15030
    hostPort: 15030
    protocol: TCP
  - containerPort: 15031
    hostPort: 15031
    protocol: TCP 
  - containerPort: 15032
    hostPort: 15032
    protocol: TCP
  - containerPort: 15443
    hostPort: 15443
    protocol: TCP
  - containerPort: 31400
    hostPort: 31400
    protocol: TCP
